name: Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Heroku
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: tiagogouvea/github-dpl-action@master
        with:
          provider: "heroku"
          app: ${{secrets.HEROKU_APP_NAME}}
          api-key: ${{secrets.HEROKU_API}}
